import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";


import regular from "next/font/local";







const general = regular({
    src: '../public/fonts/GeneralSans-Regular.ttf',
    display: 'swap',
})



const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"></link>
      </head>
      <body className={`${general.className}`} >
        {children}
      </body>
    </html>
  );
}
